branches:
  only:
    - master
    - develop

env:
  global:
    - CODECOV_ELIGIBLE=true

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode11.4
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

install:
  # Mac OS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mosquitto ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/sbin/mosquitto -c ./.travis/mosquitto.conf -d ; fi

  # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo | sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --allow-unauthenticated mosquitto ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mosquitto -c ./.travis/mosquitto.conf -d ; fi

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
