language: generic

jobs:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode11.4

install:
  # Mac OS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl mosquitto openssl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/sbin/mosquitto -c .mosquitto.conf -d ; fi

  # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo | sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mosquitto ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mosquitto -c ./mosquitto.conf -d ; fi

script:
  - swift build
  - swift test
