language: generic

jobs:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode11.4
      sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; wget https://swift.org/builds/swift-5.2.1-release/ubuntu1804/swift-5.2.1-RELEASE/swift-5.2.1-RELEASE-ubuntu18.04.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; tar xzf swift-5.2.1-RELEASE-ubuntu18.04.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; export PATH=${PWD}/swift-5.2.1-RELEASE-ubuntu18.04/usr/bin:"${PATH}" ; fi

install:
  # Mac OS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mosquitto ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/sbin/mosquitto -c ./.travis/mosquitto.conf -d ; fi

  # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo | sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mosquitto ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mosquitto -c ./.travis/mosquitto.conf -d ; fi

script:
  - swift build
  - swift test
